import type { SerializedNodesMap } from '@/lib/site-renderer/types';

const nodes: SerializedNodesMap = {
  ROOT: {
    type: {
      resolvedName: 'Container',
    },
    nodes: [
      'node-heading-default',
      'node-text-default',
      'node-button-default',
      'xtk9wLK5vv',
      'YLq62aHIOm',
      'fsPkWovjnH',
      'KrM1G53jvX',
      'Izm7zjeDUu',
      'XkKC2ay8CM',
      'kb_iudL-Z9',
      'a_tggJKuBH',
      'jr_4RE6wnF',
      'ylndCAA2zZ',
      'bevizJnVP0',
      'aK1xoHNCOS',
      'HYwBalW485',
      'q6G2JvLO7N',
      'GRrwalOZgn',
      'VLmzK0LJBn',
      'JFXR-atMbZ',
      'pdB18F3XI3',
      'tpFcxTXFyl',
      'EX1G8ly3Ar',
      'iZk3VjrWX2',
    ],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 6,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 40,
      maxWidth: '100%',
      className: '',
      direction: 'column',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: {
        type: 'radial',
        angle: 90,
        stops: [
          {
            color: '#e9eadc',
            position: 14,
          },
          {
            color: '#6a2020',
            position: 100,
          },
        ],
      },
      borderRadius: 0,
      alignVertical: 'center',
      centerContent: true,
      flexDirection: 'column',
      alignHorizontal: 'space-between',
    },
    custom: {},
    hidden: false,
    parent: null,
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  '-EoJ3-Z9do': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'VLmzK0LJBn',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  '08imy_6QBL': {
    type: {
      resolvedName: 'AccordionItemCanvas',
    },
    nodes: [],
    props: {
      placeholderLabel: 'Arraste blocos para "Terceiro item"',
    },
    custom: {},
    hidden: false,
    parent: 'Izm7zjeDUu',
    isCanvas: true,
    displayName: 'Conteúdo do item do acordeão',
    linkedNodes: {},
  },
  '0rs7VkWBan': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  '2f7gBtVPeA': {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Texto aqui',
      align: 'center',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      maxWidth: '640px',
      textSize: 16,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'Akshar',
      fontWeight: 'regular',
      lineHeight: 1.5,
      borderRadius: 0,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'M9qo2N7CL7',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  '4HO0PLNEDp': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'R6RuyaSwdp',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  '6A9KinfRHJ': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'VLmzK0LJBn',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  '6iX2ZC9tOV': {
    type: {
      resolvedName: 'Container',
    },
    nodes: [],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      maxWidth: '1200px',
      className: '',
      direction: 'column',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      borderRadius: 20,
      alignVertical: 'stretch',
      centerContent: true,
      alignHorizontal: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  '6j4AowURTB': {
    type: {
      resolvedName: 'Container',
    },
    nodes: [],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      maxWidth: '1200px',
      className: '',
      direction: 'column',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      borderRadius: 20,
      alignVertical: 'stretch',
      centerContent: true,
      alignHorizontal: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'GRrwalOZgn',
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  '7zJiAWcRsB': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 48,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'c0fN3deFwW',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  '9KGMErHVpf': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'var(--color-text-primary)',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'AirVent',
      iconSize: 96,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(24, 97, 149, 1.00)',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'pdB18F3XI3',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  ADxvJLawyu: {
    type: {
      resolvedName: 'ColumnCanvasSlot',
    },
    nodes: [],
    props: {
      style: {
        gap: 'var(--spacing-md)',
        width: '100%',
        display: 'flex',
        minHeight: '150px',
        flexDirection: 'column',
      },
      'data-column-slot': 'column-1',
    },
    custom: {},
    hidden: false,
    parent: 'GRrwalOZgn',
    isCanvas: true,
    displayName: 'Área da coluna',
    linkedNodes: {},
  },
  BK3Rr0369m: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  C0HHwRxa8M: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'rgba(230, 80, 0, 1.00)',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Airplay',
      iconSize: 88,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'pdB18F3XI3',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  DeGroLWd8x: {
    type: {
      resolvedName: 'TabPanelCanvas',
    },
    nodes: ['FanTxUyCi6'],
    props: {
      placeholderLabel: 'Arraste blocos para "Segunda aba"',
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: true,
    displayName: 'Conteúdo da aba',
    linkedNodes: {},
  },
  DiwqBC0s6i: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  ELA_ffyV6S: {
    type: {
      resolvedName: 'ColumnCanvasSlot',
    },
    nodes: [],
    props: {
      style: {
        gap: 'var(--spacing-md)',
        width: '100%',
        display: 'flex',
        minHeight: '150px',
        flexDirection: 'column',
      },
      'data-column-slot': 'column-2',
    },
    custom: {},
    hidden: false,
    parent: 'GRrwalOZgn',
    isCanvas: true,
    displayName: 'Área da coluna',
    linkedNodes: {},
  },
  EX1G8ly3Ar: {
    type: {
      resolvedName: 'Video',
    },
    nodes: [],
    props: {
      id: '',
      url: 'https://www.youtube.com/watch?v=7z5hIMiBu7o',
      loop: false,
      muted: true,
      title: 'Apresentação em vídeo',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      poster:
        'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
      shadow: 'none',
      padding: 0,
      autoPlay: false,
      controls: true,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(153, 20, 20, 1.00)',
      borderRadius: 26,
      playerHeight: '280px',
      playerAspectRatio: '16/9',
      showPlayIndicator: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Vídeo',
    linkedNodes: {},
  },
  EzLzAa6Q3j: {
    type: {
      resolvedName: 'Card',
    },
    nodes: ['rqTFbgnh_-'],
    props: {
      id: '',
      gap: 16,
      width: '100%',
      border: {
        color: '#e0e0e0',
        style: 'solid',
        width: 1,
      },
      height: 'auto',
      margin: 0,
      shadow: 'strong',
      padding: 32,
      maxWidth: '640px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'stretch',
      background: 'rgba(0, 0, 0, 0.00)',
      borderRadius: 0,
      justifyContent: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'KrM1G53jvX',
    isCanvas: true,
    displayName: 'Cartão',
    linkedNodes: {},
  },
  F0m9yA8xt7: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  FanTxUyCi6: {
    type: {
      resolvedName: 'Badge',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Etiqueta',
      width: 'auto',
      height: 'auto',
      margin: [0, 0, 0, 0],
      variant: 'solid',
      textSize: 14,
      alignment: 'flex-start',
      className: '',
      textColor: 'var(--color-accent-strong)',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-accent-soft)',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'semibold',
      borderRadius: 999,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    custom: {},
    hidden: false,
    parent: 'DeGroLWd8x',
    isCanvas: false,
    displayName: 'Badge',
    linkedNodes: {},
  },
  G4U0g_PGqU: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'rgba(230, 80, 0, 1.00)',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Airplay',
      iconSize: 88,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'pdB18F3XI3',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  GKWIZaRHzP: {
    type: {
      resolvedName: 'Container',
    },
    nodes: [],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      maxWidth: '1200px',
      className: '',
      direction: 'column',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      borderRadius: 20,
      alignVertical: 'stretch',
      centerContent: true,
      alignHorizontal: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  GRrwalOZgn: {
    type: {
      resolvedName: 'Columns',
    },
    nodes: ['YaS3O7JdSe', '6j4AowURTB'],
    props: {
      id: '',
      gap: 32,
      ratio: '50-50',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      layout: 'two',
      margin: [0, 0, 0, 0],
      shadow: 'none',
      columns: [
        {
          id: 'column-1',
          title: 'Coluna 1',
        },
        {
          id: 'column-2',
          title: 'Coluna 2',
        },
      ],
      padding: [24, 24, 24, 24],
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(51, 116, 163, 1.00)',
      borderRadius: 24,
      columnPadding: [24, 24, 24, 24],
      mobileBehavior: 'stack',
      columnBackground: 'var(--color-bg-surface)',
      columnBorderRadius: 16,
      columnVerticalAlign: 'top',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Colunas',
    linkedNodes: {
      'column-1': 'ADxvJLawyu',
      'column-2': 'ELA_ffyV6S',
    },
  },
  HYwBalW485: {
    type: {
      resolvedName: 'Timeline',
    },
    nodes: [],
    props: {
      id: '',
      items: [
        {
          id: 'timeline-1',
          date: 'Jan/2025',
          title: 'Kickoff do projeto',
          iconName: 'CalendarClock',
          description: 'Alinhe objetivos, responsáveis e cronograma.',
        },
        {
          id: 'timeline-2',
          date: 'Mar/2025',
          title: 'Primeiro release',
          iconName: 'Clock',
          description: 'Entregue a primeira versão utilizável aos usuários.',
        },
        {
          id: 'timeline-3',
          date: 'Jun/2025',
          title: 'Escala e melhorias',
          iconName: 'Shuffle',
          description: 'Itere com base em feedbacks e métricas de uso.',
        },
      ],
      width: '100%',
      height: 'auto',
      margin: [0, 0, 0, 0],
      shadow: 'none',
      itemGap: 16,
      padding: [8, 8, 8, 8],
      dateSize: 13,
      className: '',
      dateColor: 'var(--color-text-muted)',
      lineColor: 'var(--color-border-strong)',
      showIcons: true,
      titleSize: 18,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      contentGap: 8,
      itemBorder: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 1,
      },
      titleColor: 'var(--color-text-primary)',
      itemPadding: [16, 16, 16, 16],
      markerColor: 'var(--color-accent)',
      orientation: 'vertical',
      dateTransform: 'none',
      dateFontFamily: 'var(--font-family-sans)',
      dateFontWeight: 'medium',
      dateLineHeight: 1.3,
      itemBackground: 'var(--color-bg-surface)',
      titleTransform: 'none',
      descriptionSize: 15,
      titleFontFamily: 'var(--font-family-sans)',
      titleFontWeight: 'semibold',
      titleLineHeight: 1.3,
      descriptionColor: 'var(--color-text-secondary)',
      itemBorderRadius: 14,
      dateLetterSpacing: 0,
      titleLetterSpacing: 0,
      descriptionTransform: 'none',
      descriptionFontFamily: 'var(--font-family-sans)',
      descriptionFontWeight: 'regular',
      descriptionLineHeight: 1.5,
      descriptionLetterSpacing: 0,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Linha do tempo',
    linkedNodes: {},
  },
  Hyditce9CD: {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Novo texto',
      align: 'left',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      maxWidth: '640px',
      textSize: 16,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'regular',
      lineHeight: 1.5,
      borderRadius: 0,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  Izm7zjeDUu: {
    type: {
      resolvedName: 'Accordion',
    },
    nodes: [],
    props: {
      id: '',
      items: [
        {
          id: 'accordion-1',
          title: 'Primeiro item',
        },
        {
          id: 'accordion-2',
          title: 'Segundo item',
        },
        {
          id: 'accordion-3',
          title: 'Terceiro item',
        },
      ],
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: [0, 0, 0, 0],
      shadow: 'none',
      itemGap: 16,
      padding: 0,
      iconType: 'arrow',
      className: '',
      openItems: [],
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(13, 153, 255, 0.00)',
      borderRadius: 0,
      headerPadding: [16, 20, 16, 20],
      contentPadding: 0,
      headerTextSize: 16,
      headerTextAlign: 'left',
      headerTextColor: '#111827',
      contentTextColor: 'rgba(65, 42, 42, 0.00)',
      headerBackground: 'rgba(160, 143, 59, 0.74)',
      headerFontFamily: 'Akronim',
      headerFontWeight: 'medium',
      headerLineHeight: 1.4,
      itemBorderRadius: 17,
      allowMultipleOpen: true,
      contentBackground: 'rgba(58, 94, 120, 0.00)',
      headerLetterSpacing: 0,
      headerTextTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Acordeão',
    linkedNodes: {
      'accordion-1': 'fKnqezW8ib',
      'accordion-2': 'yOwk3Pf-sF',
      'accordion-3': '08imy_6QBL',
    },
  },
  'JFXR-atMbZ': {
    type: {
      resolvedName: 'List',
    },
    nodes: [],
    props: {
      id: '',
      items: [
        {
          id: 'list-item-1',
          text: 'Primeiro ponto importante',
        },
        {
          id: 'list-item-2',
          text: 'Benefício ou diferencial',
        },
        {
          id: 'list-item-3',
          text: 'Dado ou observação complementar',
        },
      ],
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 10,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      textSize: 24,
      className: '',
      textAlign: 'left',
      textColor: 'rgba(0, 0, 0, 1.00)',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'JetBrains Mono',
      fontWeight: 'bold',
      lineHeight: 1.25,
      markerIcon: 'Disc2',
      markerType: 'bullet',
      itemSpacing: 0,
      markerColor: 'rgba(0, 0, 0, 1.00)',
      borderRadius: 0,
      letterSpacing: 2.8,
      textTransform: 'uppercase',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Lista com marcadores',
    linkedNodes: {},
  },
  KrM1G53jvX: {
    type: {
      resolvedName: 'Grid',
    },
    nodes: ['S7v597Zmrd', 'wDuF_BGCEE', 'c0fN3deFwW', 'EzLzAa6Q3j'],
    props: {
      id: '',
      gap: 22,
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'end',
      background: 'rgba(255, 255, 255, 0.00)',
      borderRadius: 16,
      justifyItems: 'center',
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 2,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Grade',
    linkedNodes: {},
  },
  M9qo2N7CL7: {
    type: {
      resolvedName: 'Section',
    },
    nodes: ['2f7gBtVPeA'],
    props: {
      id: '',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: [72, 32, 72, 32],
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      alignContent: 'center',
      borderRadius: 0,
      contentWidth: 'wide',
      overlayColor: 'var(--color-bg-surface)',
      backgroundAlt: '',
      paddingPreset: 'lg',
      overlayOpacity: 0,
      backgroundImage: '',
    },
    custom: {},
    hidden: false,
    parent: 'gV6ARpBsaI',
    isCanvas: true,
    displayName: 'Seção',
    linkedNodes: {},
  },
  P_kfbXT7OS: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  R6RuyaSwdp: {
    type: {
      resolvedName: 'TabPanelCanvas',
    },
    nodes: ['4HO0PLNEDp'],
    props: {
      placeholderLabel: 'Arraste blocos para "Primeira aba"',
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: true,
    displayName: 'Conteúdo da aba',
    linkedNodes: {},
  },
  RW_MSTdhx6: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 52,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'S7v597Zmrd',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  S7v597Zmrd: {
    type: {
      resolvedName: 'Card',
    },
    nodes: ['RW_MSTdhx6'],
    props: {
      id: '',
      gap: 16,
      width: '100%',
      border: {
        color: '#e0e0e0',
        style: 'solid',
        width: 1,
      },
      height: 'auto',
      margin: 0,
      shadow: 'strong',
      padding: 32,
      maxWidth: '640px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'stretch',
      background: 'rgba(0, 0, 0, 0.00)',
      borderRadius: 0,
      justifyContent: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'KrM1G53jvX',
    isCanvas: true,
    displayName: 'Cartão',
    linkedNodes: {},
  },
  VLmzK0LJBn: {
    type: {
      resolvedName: 'Grid',
    },
    nodes: ['6A9KinfRHJ', 'xg-ysvFTxq', '-EoJ3-Z9do'],
    props: {
      id: '',
      gap: 24,
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'start',
      background: 'var(--color-bg-surface)',
      borderRadius: 16,
      justifyItems: 'stretch',
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 3,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Grade',
    linkedNodes: {},
  },
  XkKC2ay8CM: {
    type: {
      resolvedName: 'IconCard',
    },
    nodes: [],
    props: {
      id: '',
      title: 'Título do cartão',
      width: '350px',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 1,
      },
      height: 'auto',
      margin: [0, 0, 0, 0],
      shadow: 'soft',
      padding: [20, 20, 20, 20],
      textGap: 8,
      iconName: 'AirVent',
      iconSize: 50,
      className: '',
      iconColor: 'var(--color-accent-strong)',
      textAlign: 'center',
      titleSize: 21,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-surface)',
      contentGap: 16,
      titleColor: 'var(--color-text-primary)',
      description:
        'Explique em poucas linhas o benefício ou resultado que o seu cliente terá. Seja direto e mantenha o texto curto.',
      borderRadius: 16,
      iconPosition: 'top',
      titleTransform: 'none',
      descriptionSize: 15,
      titleFontFamily: 'Averia Libre',
      titleFontWeight: 'semibold',
      titleLineHeight: 1.35,
      descriptionColor: 'var(--color-text-secondary)',
      titleLetterSpacing: 0,
      descriptionTransform: 'none',
      descriptionFontFamily: 'Alkalami',
      descriptionFontWeight: 'regular',
      descriptionLineHeight: 1.5,
      descriptionLetterSpacing: 0,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Cartão com ícone',
    linkedNodes: {},
  },
  YLq62aHIOm: {
    type: {
      resolvedName: 'Divider',
    },
    nodes: [],
    props: {
      id: '',
      color: 'rgba(93, 4, 4, 1.00)',
      width: '100%',
      height: '1px',
      margin: 10,
      alignment: 'center',
      className: '',
      lineStyle: 'solid',
      thickness: 5,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      orientation: 'horizontal',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Divisor',
    linkedNodes: {},
  },
  YaS3O7JdSe: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'GRrwalOZgn',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  aK1xoHNCOS: {
    type: {
      resolvedName: 'Avatar',
    },
    nodes: [],
    props: {
      id: '',
      alt: 'Foto de perfil',
      src: 'https://pub-da297c2772894ddb803d91c4dbd610ad.r2.dev/cmhuwrvln0000txygnhcylbgg/e7497646-1fee-4ff2-83ff-8fb359e29cc0.png',
      size: 'md',
      width: 'auto',
      border: {
        color: 'var(--color-border-strong)',
        style: 'solid',
        width: 2,
      },
      height: 'auto',
      margin: [0, 0, 0, 0],
      padding: 0,
      fontSize: 22,
      initials: 'AB',
      className: '',
      textColor: 'var(--color-text-primary)',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'semibold',
      showBorder: true,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Avatar',
    linkedNodes: {},
  },
  a_tggJKuBH: {
    type: {
      resolvedName: 'Stat',
    },
    nodes: [],
    props: {
      id: '',
      gap: 11,
      label: 'Usuários ativos por mês',
      value: '3.2',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: [0, 0, 0, 0],
      shadow: 'none',
      suffix: 'M',
      padding: [12, 12, 12, 12],
      className: '',
      labelSize: 20,
      textAlign: 'center',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-surface)',
      labelColor: 'var(--color-text-secondary)',
      numberSize: 21,
      numberColor: 'var(--color-text-primary)',
      borderRadius: 12,
      labelTransform: 'none',
      labelFontFamily: 'Euphoria Script',
      labelFontWeight: 'medium',
      labelLineHeight: 1.4,
      numberTransform: 'none',
      numberFontFamily: 'Aguafina Script',
      numberFontWeight: 'bold',
      numberLineHeight: 1,
      labelLetterSpacing: 0,
      numberLetterSpacing: -1,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Estatística',
    linkedNodes: {},
  },
  bevizJnVP0: {
    type: {
      resolvedName: 'ImageOverlay',
    },
    nodes: ['zLR6h4bCQt'],
    props: {
      id: '',
      width: '110%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: '80vh',
      margin: [0, 0, 0, 0],
      shadow: 'soft',
      padding: 0,
      imageAlt: 'Imagem de fundo',
      imageSrc:
        'https://pub-da297c2772894ddb803d91c4dbd610ad.r2.dev/cmhuwrvln0000txygnhcylbgg/c7d0619b-c326-4ccc-8f62-e229526cf194.png',
      className: '',
      minHeight: '50vh',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-surface)',
      borderRadius: 0,
      overlayColor: 'var(--color-bg-strong)',
      overlayOpacity: 45,
      contentMaxWidth: '88px',
      contentVerticalAlign: 'center',
      contentHorizontalAlign: 'center',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Imagem com Sobreposição',
    linkedNodes: {},
  },
  c0fN3deFwW: {
    type: {
      resolvedName: 'Card',
    },
    nodes: ['7zJiAWcRsB'],
    props: {
      id: '',
      gap: 16,
      width: '100%',
      border: {
        color: '#e0e0e0',
        style: 'solid',
        width: 1,
      },
      height: 'auto',
      margin: 0,
      shadow: 'strong',
      padding: 32,
      maxWidth: '640px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'stretch',
      background: 'rgba(0, 0, 0, 0.00)',
      borderRadius: 0,
      justifyContent: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'KrM1G53jvX',
    isCanvas: true,
    displayName: 'Cartão',
    linkedNodes: {},
  },
  fKnqezW8ib: {
    type: {
      resolvedName: 'AccordionItemCanvas',
    },
    nodes: ['iLLIZ1NeVb'],
    props: {
      placeholderLabel: 'Arraste blocos para "Primeiro item"',
    },
    custom: {},
    hidden: false,
    parent: 'Izm7zjeDUu',
    isCanvas: true,
    displayName: 'Conteúdo do item do acordeão',
    linkedNodes: {},
  },
  fg9c5gxkVK: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 52,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'wDuF_BGCEE',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  fsPkWovjnH: {
    type: {
      resolvedName: 'Badge',
    },
    nodes: [],
    props: {
      id: '',
      size: 'lg',
      text: 'Etiqueta',
      width: 'auto',
      height: 'auto',
      margin: [0, 0, 0, 0],
      variant: 'outline',
      textSize: 32,
      alignment: 'flex-start',
      className: '',
      textColor: 'var(--color-accent-strong)',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(54, 98, 129, 1.00)',
      fontFamily: 'Atomic Age',
      fontWeight: 'semibold',
      borderRadius: 999,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Badge',
    linkedNodes: {},
  },
  gV6ARpBsaI: {
    type: {
      resolvedName: 'TabPanelCanvas',
    },
    nodes: ['M9qo2N7CL7'],
    props: {
      placeholderLabel: 'Arraste blocos para "Terceira aba"',
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: true,
    displayName: 'Conteúdo da aba',
    linkedNodes: {},
  },
  iLLIZ1NeVb: {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Você sabe que nao da',
      align: 'left',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      maxWidth: '640px',
      textSize: 16,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'regular',
      lineHeight: 1.5,
      borderRadius: 0,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'fKnqezW8ib',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  iZk3VjrWX2: {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: 'https://meusite.com/cta',
      size: 'md',
      text: 'Clique aqui',
      label: 'Chamar para ação',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'solid',
      iconName: 'ArrowRight',
      showIcon: true,
      textSize: 16,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: '#ffffff',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: '#0d99ff',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'semibold',
      showShadow: true,
      borderRadius: 999,
      openInNewTab: false,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  jr_4RE6wnF: {
    type: {
      resolvedName: 'Gallery',
    },
    nodes: [],
    props: {
      id: '',
      gap: 0,
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      images: [
        {
          id: 'gallery-2',
          alt: 'Pessoa apresentando um dashboard',
          src: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
          caption: 'Apresente resultados e progresso',
        },
        {
          id: 'gallery-1',
          alt: 'Equipe colaborando em um laptop',
          src: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
          caption: 'Mostre sua equipe em ação',
        },
        {
          id: 'gallery-3',
          alt: 'Tela com código e interface gráfica',
          src: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=1200&q=80',
          caption: 'Mostre a parte técnica do produto',
        },
        {
          id: 'gallery-4',
          alt: 'Designer ajustando detalhes em notebook',
          src: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
          caption: 'Capriche nos detalhes visuais',
        },
        {
          id: 'gallery-5',
          alt: 'Trabalho colaborativo em mesa',
          src: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
          caption: 'Integração entre times',
        },
      ],
      margin: 0,
      shadow: 'none',
      columns: 3,
      padding: 0,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      hoverEffect: 'darken',
      openInModal: true,
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Galeria de imagens',
    linkedNodes: {},
  },
  kH5TNz3bZV: {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: 'https://meusite.com/cta',
      size: 'md',
      text: 'Clique aqui',
      label: ' ação',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'solid',
      iconName: 'ArrowRight',
      showIcon: false,
      textSize: 16,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: '#111827',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: '#0d99ff',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'semibold',
      showShadow: true,
      borderRadius: 999,
      openInNewTab: false,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'xtk9wLK5vv',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  'kb_iudL-Z9': {
    type: {
      resolvedName: 'Callout',
    },
    nodes: [],
    props: {
      id: '',
      tone: 'info',
      title: 'Destaque o ponto principal aqui',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: [0, 0, 0, 0],
      shadow: 'soft',
      padding: [16, 20, 16, 20],
      textGap: 6,
      iconName: 'Megaphone',
      iconSize: 28,
      showIcon: true,
      className: '',
      iconColor: 'var(--color-info)',
      textAlign: 'center',
      titleSize: 18,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-info-soft)',
      contentGap: 12,
      showAccent: true,
      titleColor: 'var(--color-text-primary)',
      accentColor: 'var(--color-info)',
      accentWidth: 4,
      description:
        'Use esta área para avisos, instruções rápidas ou mensagens importantes para quem visita sua página.',
      borderRadius: 14,
      titleTransform: 'none',
      descriptionSize: 15,
      titleFontFamily: 'Aclonica',
      titleFontWeight: 'semibold',
      titleLineHeight: 1.35,
      descriptionColor: 'var(--color-text-secondary)',
      titleLetterSpacing: 0,
      descriptionTransform: 'none',
      descriptionFontFamily: 'Aguafina Script',
      descriptionFontWeight: 'regular',
      descriptionLineHeight: 1,
      descriptionLetterSpacing: 0,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Caixa de destaque',
    linkedNodes: {},
  },
  mqGp0zW22V: {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Novo texto',
      align: 'left',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      maxWidth: '640px',
      textSize: 16,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'regular',
      lineHeight: 1.5,
      borderRadius: 0,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'xtk9wLK5vv',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  pDuFoBpYIh: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'rgba(230, 80, 0, 1.00)',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Airplay',
      iconSize: 88,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'pdB18F3XI3',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  pdB18F3XI3: {
    type: {
      resolvedName: 'Container',
    },
    nodes: ['C0HHwRxa8M', 'G4U0g_PGqU', 'tChLgKVhsx', 'pDuFoBpYIh', '9KGMErHVpf'],
    props: {
      id: '',
      gap: 30,
      wrap: false,
      width: 'auto',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      maxWidth: '1200px',
      className: '',
      direction: 'row',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      borderRadius: 20,
      alignVertical: 'center',
      centerContent: true,
      alignHorizontal: 'center',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  q6G2JvLO7N: {
    type: {
      resolvedName: 'Tabs',
    },
    nodes: [
      '0rs7VkWBan',
      'Hyditce9CD',
      '6iX2ZC9tOV',
      'BK3Rr0369m',
      'P_kfbXT7OS',
      'F0m9yA8xt7',
      'DiwqBC0s6i',
      'GKWIZaRHzP',
      'v57FYFpzNj',
      's5HY3ppMZs',
    ],
    props: {
      id: '',
      tabs: [
        {
          id: 'tab-hero',
          title: 'Primeira aba',
        },
        {
          id: 'tab-features',
          title: 'Segunda aba',
        },
        {
          id: 'tab-extra',
          title: 'Terceira aba',
        },
      ],
      width: '100%',
      border: {
        color: '#af1212',
        style: 'solid',
        width: 5,
      },
      height: 'auto',
      margin: [0, 0, 0, 0],
      shadow: 'none',
      padding: [16, 16, 16, 16],
      variant: 'line',
      tabColor: 'var(--color-text-secondary)',
      alignTabs: 'stretch',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      tabPadding: 5,
      tabSpacing: 26,
      activeTabId: 'tab-hero',
      orientation: 'horizontal',
      tabTextSize: 16,
      borderRadius: 24,
      tabBackground: 'transparent',
      tabFontFamily: 'Atomic Age',
      tabFontWeight: 'medium',
      contentPadding: [24, 24, 24, 24],
      indicatorColor: 'var(--color-accent)',
      tabActiveColor: 'var(--color-text-primary)',
      tabBorderRadius: 20,
      tabTextTransform: 'none',
      contentBackground: 'var(--color-bg-surface)',
      contentBorderRadius: 16,
      tabActiveBackground: 'var(--color-bg-surface)',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Abas',
    linkedNodes: {
      'tab-hero': 'R6RuyaSwdp',
      'tab-extra': 'gV6ARpBsaI',
      'tab-features': 'DeGroLWd8x',
    },
  },
  'q8PU0fX-7S': {
    type: {
      resolvedName: 'Heading',
    },
    nodes: [],
    props: {
      id: '',
      seo: {
        text: 'Título a  a  a  a',
        level: 'h2',
      },
      text: 'Título a  a  a  a',
      align: 'left',
      color: 'rgba(13, 153, 255, 1.00)',
      level: 'h2',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      weight: 'bold',
      padding: 0,
      emphasis: true,
      fontSize: 36,
      maxWidth: '720px',
      className: '',
      uppercase: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'Grechen Fuemen',
      lineHeight: 1.2,
      borderRadius: 0,
      spacingBelow: 0,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'xtk9wLK5vv',
    isCanvas: false,
    displayName: 'Título',
    linkedNodes: {},
  },
  'rqTFbgnh_-': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'rgba(0, 0, 0, 1.00)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Airplay',
      iconSize: 52,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'EzLzAa6Q3j',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  s5HY3ppMZs: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Star',
      iconSize: 32,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  tChLgKVhsx: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'rgba(230, 80, 0, 1.00)',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Airplay',
      iconSize: 88,
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'pdB18F3XI3',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  tpFcxTXFyl: {
    type: {
      resolvedName: 'Video',
    },
    nodes: [],
    props: {
      id: '',
      url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
      loop: false,
      muted: true,
      title: 'Apresentação em vídeo',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      poster:
        'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
      shadow: 'soft',
      padding: 0,
      autoPlay: false,
      controls: true,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(0, 0, 0, 0.47)',
      borderRadius: 6,
      playerHeight: '280px',
      playerAspectRatio: '16/9',
      showPlayIndicator: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Vídeo',
    linkedNodes: {},
  },
  v57FYFpzNj: {
    type: {
      resolvedName: 'Container',
    },
    nodes: [],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      maxWidth: '1200px',
      className: '',
      direction: 'column',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-subtle)',
      borderRadius: 20,
      alignVertical: 'stretch',
      centerContent: true,
      alignHorizontal: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'q6G2JvLO7N',
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  wDuF_BGCEE: {
    type: {
      resolvedName: 'Card',
    },
    nodes: ['fg9c5gxkVK'],
    props: {
      id: '',
      gap: 16,
      width: '100%',
      border: {
        color: '#e0e0e0',
        style: 'solid',
        width: 1,
      },
      height: 'auto',
      margin: 0,
      shadow: 'strong',
      padding: 32,
      maxWidth: '640px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'stretch',
      background: 'rgba(0, 0, 0, 0.00)',
      borderRadius: 0,
      justifyContent: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'KrM1G53jvX',
    isCanvas: true,
    displayName: 'Cartão',
    linkedNodes: {},
  },
  'xg-ysvFTxq': {
    type: {
      resolvedName: 'Badge',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Etiqueta',
      width: 'auto',
      height: 'auto',
      margin: [0, 0, 0, 0],
      variant: 'solid',
      textSize: 14,
      alignment: 'flex-start',
      className: '',
      textColor: 'var(--color-accent-strong)',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-accent-soft)',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'semibold',
      borderRadius: 999,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'VLmzK0LJBn',
    isCanvas: false,
    displayName: 'Badge',
    linkedNodes: {},
  },
  xtk9wLK5vv: {
    type: {
      resolvedName: 'Card',
    },
    nodes: ['q8PU0fX-7S', 'mqGp0zW22V', 'kH5TNz3bZV'],
    props: {
      id: '',
      gap: 0,
      width: '100%',
      border: {
        color: '#2f4589',
        style: 'dashed',
        width: 2,
      },
      height: 'auto',
      margin: 0,
      shadow: 'strong',
      padding: 32,
      maxWidth: '300px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'flex-start',
      background: 'rgba(0, 0, 0, 0.61)',
      borderRadius: 23,
      justifyContent: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Cartão',
    linkedNodes: {},
  },
  'yOwk3Pf-sF': {
    type: {
      resolvedName: 'AccordionItemCanvas',
    },
    nodes: [],
    props: {
      placeholderLabel: 'Arraste blocos para "Segundo item"',
    },
    custom: {},
    hidden: false,
    parent: 'Izm7zjeDUu',
    isCanvas: true,
    displayName: 'Conteúdo do item do acordeão',
    linkedNodes: {},
  },
  ylndCAA2zZ: {
    type: {
      resolvedName: 'Map',
    },
    nodes: [],
    props: {
      id: '',
      zoom: 14,
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: '360px',
      margin: [0, 0, 0, 0],
      shadow: 'soft',
      mapType: 'roadmap',
      padding: [0, 0, 0, 0],
      location: 'Avenida Paulista, São Paulo',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-surface)',
      borderRadius: 14,
      showControls: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Mapa / Google Maps',
    linkedNodes: {},
  },
  zLR6h4bCQt: {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Novo texto',
      align: 'left',
      color: 'var(--color-text-primary)',
      width: 'auto',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      maxWidth: 'auto',
      textSize: 16,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(255, 255, 255, 1.00)',
      fontFamily: 'Amiko',
      fontWeight: 'regular',
      lineHeight: 1.5,
      borderRadius: 0,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'bevizJnVP0',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  'node-text-default': {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Arraste componentes para cá e comece a montar sua página.',
      align: 'center',
      color: '#4a3f78',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      fontSize: 18,
      maxWidth: '1200px',
      textSize: 16,
      className: '',
      textAlign: 'center',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 400,
      lineHeight: 1.5,
      borderRadius: 0,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  'node-button-default': {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: '',
      size: 'lg',
      text: 'Adicionar bloco',
      label: 'Chamar para ação',
      width: '100%',
      border: {
        color: '#CBD5F5',
        style: 'solid',
        width: 20,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'solid',
      iconName: 'Airplay',
      showIcon: false,
      textSize: 16,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: 'rgba(255, 255, 255, 1.00)',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(0, 149, 255, 1.00)',
      fontFamily: 'var(--font-family-sans)',
      fontWeight: 'semibold',
      showShadow: true,
      borderRadius: 120,
      openInNewTab: true,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  'node-heading-default': {
    type: {
      resolvedName: 'Heading',
    },
    nodes: [],
    props: {
      id: '',
      seo: {
        text: 'Apresente o principal benefício com um título impactante.',
        level: 'h2',
      },
      text: 'Bem-vindo ao novo editor',
      align: 'center',
      color: '#1f1843',
      level: 'h2',
      width: '100%',
      border: {
        color: '#000000',
        style: 'dashed',
        width: 10,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      weight: 'bold',
      padding: 0,
      emphasis: false,
      fontSize: 36,
      maxWidth: '1200px',
      className: '',
      textAlign: 'center',
      uppercase: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontFamily: 'Alumni Sans Collegiate One',
      lineHeight: 1.2,
      borderRadius: 0,
      spacingBelow: 16,
      letterSpacing: 0,
      textTransform: 'none',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Título',
    linkedNodes: {},
  },
};

export default nodes;
