const nodes = {
  ROOT: {
    type: {
      resolvedName: 'Container',
    },
    nodes: [
      'node-heading-default',
      'node-text-default',
      'node-button-default',
      '0y3xHZhj-6',
      'kQXhwJ0n03',
      'EX1G8ly3Ar',
      'iZk3VjrWX2',
    ],
    props: {
      gap: 24,
      wrap: false,
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 6,
      },
      margin: 0,
      shadow: 'none',
      padding: 40,
      maxWidth: '1200px',
      direction: 'column',
      background: {
        type: 'radial',
        angle: 90,
        stops: [
          {
            color: '#ff0000',
            position: 25,
          },
          {
            color: '#235c86',
            position: 100,
          },
        ],
      },
      borderRadius: 0,
      alignVertical: 'stretch',
      centerContent: true,
      flexDirection: 'column',
      alignHorizontal: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: null,
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  '0y3xHZhj-6': {
    type: {
      resolvedName: 'TestControlsBlock',
    },
    nodes: [],
    props: {
      title: 'Experimente os Controles',
      width: '100%',
      border: {
        color: '#000000',
        style: 'solid',
        width: 12,
      },
      height: 'auto',
      padding: 32,
      variant: 'primary',
      iconName: 'Sparkles',
      imageAlt: 'Equipe colaborando',
      imageUrl:
        'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=900&q=80',
      alignment: 'center',
      background: '#ffffff',
      description: 'Ajuste os controles na barra lateral para ver as mudanças em tempo real.',
      borderRadius: 24,
      showHighlight: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Bloco de Teste',
    linkedNodes: {},
  },
  EX1G8ly3Ar: {
    type: {
      resolvedName: 'Video',
    },
    nodes: [],
    props: {
      url: 'https://www.youtube.com/watch?v=7z5hIMiBu7o',
      loop: false,
      muted: true,
      title: 'Apresentação em vídeo',
      width: '50%',
      height: '360px',
      poster:
        'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
      shadow: 'soft',
      autoPlay: false,
      controls: true,
      background: '#000000',
      borderRadius: 24,
      showPlayIndicator: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Vídeo',
    linkedNodes: {},
  },
  iZk3VjrWX2: {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      href: 'https://meusite.com/cta',
      size: 'md',
      text: 'Clique aqui',
      label: 'Chamar para ação',
      variant: 'solid',
      iconName: 'ArrowRight',
      showIcon: true,
      alignment: 'center',
      fullWidth: false,
      textColor: '#ffffff',
      background: '#0d99ff',
      showShadow: true,
      borderRadius: 999,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  kQXhwJ0n03: {
    type: {
      resolvedName: 'Image',
    },
    nodes: [],
    props: {
      alt: 'Equipe colaborando em um projeto criativo',
      seo: {
        alt: 'Equipe colaborando em um projeto criativo',
        title: 'Foto da equipe',
        caption: 'Legenda da imagem para descrever o contexto.',
      },
      src: 'https://pub-da297c2772894ddb803d91c4dbd610ad.r2.dev/cmhuwrvln0000txygnhcylbgg/07e4dda0-0849-4629-bcd4-e3a172b185bf.jpg',
      width: '160px',
      height: 'auto',
      shadow: 'soft',
      caption: 'Legenda da imagem para descrever o contexto.',
      linkHref: '',
      alignment: 'center',
      objectFit: 'cover',
      showFrame: false,
      frameColor: '#ffffff',
      showCaption: false,
      borderRadius: 80,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Imagem',
    linkedNodes: {},
  },
  'node-text-default': {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      text: 'Arraste componentes para cá e comece a montar sua página.',
      align: 'center',
      color: '#4a3f78',
      padding: 0,
      variant: 'body',
      fontSize: 18,
      maxWidth: '1200px',
      textAlign: 'center',
      fontWeight: 400,
      lineHeight: 1.5,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  'node-button-default': {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      href: 'https://meusite.com/cta',
      size: 'large',
      text: 'Adicionar bloco',
      label: 'Chamar para ação',
      variant: 'primary',
      iconName: 'ArrowRight',
      showIcon: true,
      alignment: 'center',
      fullWidth: false,
      textColor: '#ffffff',
      background: '#0d99ff',
      showShadow: true,
      borderRadius: 999,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  'node-heading-default': {
    type: {
      resolvedName: 'Heading',
    },
    nodes: [],
    props: {
      seo: {
        text: 'Apresente o principal benefício com um título impactante.',
        level: 'h2',
      },
      text: 'Bem-vindo ao novo editor',
      align: 'center',
      color: '#1f1843',
      level: 'h2',
      weight: 'bold',
      emphasis: false,
      maxWidth: '1200px',
      textAlign: 'center',
      uppercase: false,
      spacingBelow: 16,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Título',
    linkedNodes: {},
  },
} as const;

export default nodes;
