import type { SerializedNodesMap } from '@/lib/site-renderer/types';

const nodes: SerializedNodesMap = {
  ROOT: {
    type: {
      resolvedName: 'Container',
    },
    nodes: ['node-heading-default', 'node-text-default', 'node-button-default'],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 40,
      maxWidth: '1200px',
      className: '',
      direction: 'column',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'var(--color-bg-surface-solid)',
      borderRadius: 20,
      alignVertical: 'stretch',
      centerContent: true,
      flexDirection: 'column',
      alignHorizontal: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: null,
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  'node-text-default': {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Arraste componentes para cá e comece a montar sua página.',
      align: 'left',
      color: '#4a3f78',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      fontSize: 18,
      maxWidth: '640px',
      className: '',
      textAlign: 'center',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontWeight: 400,
      lineHeight: 1.5,
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  'node-button-default': {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: 'https://meusite.com/cta',
      size: 'large',
      text: 'Adicionar bloco',
      label: 'Chamar para ação',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'primary',
      iconName: 'ArrowRight',
      showIcon: true,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: '#ffffff',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: '#0d99ff',
      borderRadius: 999,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  'node-heading-default': {
    type: {
      resolvedName: 'Heading',
    },
    nodes: [],
    props: {
      id: '',
      seo: {
        text: 'Apresente o principal benefício com um título impactante.',
        level: 'h2',
      },
      text: 'Bem-vindo ao novo editor',
      align: 'left',
      color: '#1f1843',
      level: 'h2',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      weight: 'bold',
      padding: 0,
      emphasis: true,
      maxWidth: '720px',
      className: '',
      textAlign: 'center',
      uppercase: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
      spacingBelow: 16,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Título',
    linkedNodes: {},
  },
};

export default nodes;
