import type { SerializedNodesMap } from '@/lib/site-renderer/types';

const nodes: SerializedNodesMap = {
  ROOT: {
    type: {
      resolvedName: 'Container',
    },
    nodes: [
      'node-heading-default',
      'node-text-default',
      'node-button-default',
      'xtk9wLK5vv',
      '8tXt4ee6lc',
      'H2KqCAL1-9',
      'tpFcxTXFyl',
      'kQXhwJ0n03',
      'EX1G8ly3Ar',
      'iZk3VjrWX2',
    ],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 6,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 40,
      maxWidth: '100%',
      className: '',
      direction: 'column',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: {
        type: 'radial',
        angle: 90,
        stops: [
          {
            color: '#99a03b',
            position: 25,
          },
          {
            color: '#235c86',
            position: 100,
          },
        ],
      },
      borderRadius: 0,
      alignVertical: 'center',
      centerContent: true,
      flexDirection: 'column',
      alignHorizontal: 'center',
    },
    custom: {},
    hidden: false,
    parent: null,
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  '2uyg6rGaDC': {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: 'https://meusite.com/cta',
      size: 'md',
      text: 'Clique aqui',
      label: ' ação',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'solid',
      iconName: 'ArrowRight',
      showIcon: true,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: '#ffffff',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: '#0d99ff',
      showShadow: true,
      borderRadius: 999,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: '8tXt4ee6lc',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  '8tXt4ee6lc': {
    type: {
      resolvedName: 'Card',
    },
    nodes: ['EyPHXmQ2ml', 'BOTx3CP7QZ', 'EJSncAKKiU', '2uyg6rGaDC'],
    props: {
      id: '',
      gap: 23,
      width: '100%',
      border: {
        color: '#2f4589',
        style: 'dashed',
        width: 6,
      },
      height: 'auto',
      margin: 0,
      shadow: 'strong',
      padding: 32,
      maxWidth: '300px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'flex-start',
      background: 'rgba(57, 132, 99, 0.54)',
      borderRadius: 23,
      justifyContent: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Cartão',
    linkedNodes: {},
  },
  '9KGMErHVpf': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'var(--color-text-primary)',
      width: '010%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'AlarmClockPlus',
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(24, 97, 149, 1.00)',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'H2KqCAL1-9',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  B76HqjafSf: {
    type: {
      resolvedName: 'Image',
    },
    nodes: [],
    props: {
      id: '',
      alt: 'Equipe colaborando em um projeto criativo',
      seo: {
        alt: 'Equipe colaborando em um projeto criativo',
        title: 'Foto da equipe',
        caption: 'Legenda da imagem para descrever o contexto.',
      },
      src: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1200&q=80',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      caption: 'Legenda da imagem para descrever o contexto.',
      padding: 0,
      linkHref: '',
      alignment: 'center',
      className: '',
      objectFit: 'scale-down',
      showFrame: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      frameColor: '#ffffff',
      showCaption: false,
      borderRadius: 0,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'xtk9wLK5vv',
    isCanvas: false,
    displayName: 'Imagem',
    linkedNodes: {},
  },
  BOTx3CP7QZ: {
    type: {
      resolvedName: 'Heading',
    },
    nodes: [],
    props: {
      id: '',
      seo: {
        text: 'Título a  a  a  a',
        level: 'h2',
      },
      text: 'Título a  a  a  a',
      align: 'left',
      color: 'rgba(13, 153, 255, 1.00)',
      level: 'h2',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      weight: 'bold',
      padding: 0,
      emphasis: true,
      maxWidth: '720px',
      className: '',
      uppercase: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
      spacingBelow: 0,
    },
    custom: {},
    hidden: false,
    parent: '8tXt4ee6lc',
    isCanvas: false,
    displayName: 'Título',
    linkedNodes: {},
  },
  EJSncAKKiU: {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Novo texto',
      align: 'left',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      maxWidth: '640px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontWeight: 'regular',
      lineHeight: 1.5,
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: '8tXt4ee6lc',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  EX1G8ly3Ar: {
    type: {
      resolvedName: 'Video',
    },
    nodes: [],
    props: {
      id: '',
      url: 'https://www.youtube.com/watch?v=7z5hIMiBu7o',
      loop: false,
      muted: true,
      title: 'Apresentação em vídeo',
      width: '50%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: '360px',
      margin: 0,
      poster:
        'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
      shadow: 'none',
      padding: 0,
      autoPlay: false,
      controls: true,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(153, 20, 20, 1.00)',
      borderRadius: 24,
      showPlayIndicator: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Vídeo',
    linkedNodes: {},
  },
  EyPHXmQ2ml: {
    type: {
      resolvedName: 'Image',
    },
    nodes: [],
    props: {
      id: '',
      alt: 'Equipe colaborando em um projeto criativo',
      seo: {
        alt: 'Equipe colaborando em um projeto criativo',
        title: 'Foto da equipe',
        caption: 'Legenda da imagem para descrever o contexto.',
      },
      src: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1200&q=80',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      caption: 'Legenda da imagem para descrever o contexto.',
      padding: 0,
      linkHref: '',
      alignment: 'center',
      className: '',
      objectFit: 'scale-down',
      showFrame: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      frameColor: '#ffffff',
      showCaption: false,
      borderRadius: 0,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: '8tXt4ee6lc',
    isCanvas: false,
    displayName: 'Imagem',
    linkedNodes: {},
  },
  GoijbNmYFn: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'var(--color-text-primary)',
      width: '010%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'AlarmClockOff',
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(24, 97, 149, 1.00)',
      borderRadius: 16,
    },
    custom: {},
    hidden: false,
    parent: 'H2KqCAL1-9',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  'H2KqCAL1-9': {
    type: {
      resolvedName: 'Container',
    },
    nodes: ['9KGMErHVpf', 'GoijbNmYFn', 'HA7-worr4n', 'o8o2pOUuvp'],
    props: {
      id: '',
      gap: 24,
      wrap: false,
      width: '100%',
      border: {
        color: '#d4d4d8',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 24,
      maxWidth: '1200px',
      className: '',
      direction: 'row',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(255, 255, 255, 0.00)',
      borderRadius: 20,
      alignVertical: 'center',
      centerContent: true,
      alignHorizontal: 'center',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Container',
    linkedNodes: {},
  },
  'HA7-worr4n': {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'rgba(230, 80, 0, 1.00)',
      width: '10%',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'AlarmClock',
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'H2KqCAL1-9',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  iZk3VjrWX2: {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: 'https://meusite.com/cta',
      size: 'md',
      text: 'Clique aqui',
      label: 'Chamar para ação',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'solid',
      iconName: 'ArrowRight',
      showIcon: true,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: '#ffffff',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: '#0d99ff',
      showShadow: true,
      borderRadius: 999,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  kH5TNz3bZV: {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: 'https://meusite.com/cta',
      size: 'md',
      text: 'Clique aqui',
      label: ' ação',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'solid',
      iconName: 'ArrowRight',
      showIcon: true,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: '#111827',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: '#0d99ff',
      showShadow: true,
      borderRadius: 999,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'xtk9wLK5vv',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  kQXhwJ0n03: {
    type: {
      resolvedName: 'Image',
    },
    nodes: [],
    props: {
      id: '',
      alt: 'Equipe colaborando em um projeto criativo',
      seo: {
        alt: 'Equipe colaborando em um projeto criativo',
        title: 'Foto da equipe',
        caption: 'Legenda da imagem para descrever o contexto.',
      },
      src: 'https://pub-da297c2772894ddb803d91c4dbd610ad.r2.dev/cmhuwrvln0000txygnhcylbgg/07e4dda0-0849-4629-bcd4-e3a172b185bf.jpg',
      width: '160px',
      border: {
        color: '#3615b7',
        style: 'solid',
        width: 10,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      caption: 'Legenda da imagem para descrever o contexto.',
      padding: 0,
      linkHref: '',
      alignment: 'center',
      className: '',
      objectFit: 'cover',
      showFrame: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      frameColor: '#ffffff',
      showCaption: false,
      borderRadius: 80,
      openInNewTab: false,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Imagem',
    linkedNodes: {},
  },
  mqGp0zW22V: {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Novo texto',
      align: 'left',
      color: 'var(--color-text-primary)',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      maxWidth: '640px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontWeight: 'regular',
      lineHeight: 1.5,
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'xtk9wLK5vv',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  o8o2pOUuvp: {
    type: {
      resolvedName: 'Icon',
    },
    nodes: [],
    props: {
      id: '',
      size: 'xl',
      color: 'rgba(230, 80, 0, 1.00)',
      width: '10%',
      border: {
        color: 'var(--color-border)',
        style: 'solid',
        width: 8,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      iconName: 'Airplay',
      alignment: 'center',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'H2KqCAL1-9',
    isCanvas: false,
    displayName: 'Ícone',
    linkedNodes: {},
  },
  'q8PU0fX-7S': {
    type: {
      resolvedName: 'Heading',
    },
    nodes: [],
    props: {
      id: '',
      seo: {
        text: 'Título a  a  a  a',
        level: 'h2',
      },
      text: 'Título a  a  a  a',
      align: 'left',
      color: 'rgba(13, 153, 255, 1.00)',
      level: 'h2',
      width: '100%',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      weight: 'bold',
      padding: 0,
      emphasis: true,
      maxWidth: '720px',
      className: '',
      uppercase: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
      spacingBelow: 0,
    },
    custom: {},
    hidden: false,
    parent: 'xtk9wLK5vv',
    isCanvas: false,
    displayName: 'Título',
    linkedNodes: {},
  },
  tpFcxTXFyl: {
    type: {
      resolvedName: 'Video',
    },
    nodes: [],
    props: {
      id: '',
      url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
      loop: false,
      muted: true,
      title: 'Apresentação em vídeo',
      width: 'auto',
      border: {
        color: 'var(--color-border)',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      poster:
        'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
      shadow: 'soft',
      padding: 0,
      autoPlay: false,
      controls: true,
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(0, 0, 0, 0.00)',
      borderRadius: 9,
      showPlayIndicator: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Vídeo',
    linkedNodes: {},
  },
  xtk9wLK5vv: {
    type: {
      resolvedName: 'Card',
    },
    nodes: ['B76HqjafSf', 'q8PU0fX-7S', 'mqGp0zW22V', 'kH5TNz3bZV'],
    props: {
      id: '',
      gap: 23,
      width: '100%',
      border: {
        color: '#2f4589',
        style: 'dashed',
        width: 6,
      },
      height: 'auto',
      margin: 0,
      shadow: 'strong',
      padding: 32,
      maxWidth: '300px',
      className: '',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      alignItems: 'flex-start',
      background: 'rgba(57, 132, 99, 0.54)',
      borderRadius: 23,
      justifyContent: 'flex-start',
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'Cartão',
    linkedNodes: {},
  },
  'node-text-default': {
    type: {
      resolvedName: 'Text',
    },
    nodes: [],
    props: {
      id: '',
      text: 'Arraste componentes para cá e comece a montar sua página.',
      align: 'center',
      color: '#4a3f78',
      width: '100%',
      border: {
        color: 'transparent',
        style: 'none',
        width: 0,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      padding: 0,
      variant: 'body',
      fontSize: 18,
      maxWidth: '1200px',
      className: '',
      textAlign: 'center',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      fontWeight: 400,
      lineHeight: 1.5,
      borderRadius: 0,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Texto',
    linkedNodes: {},
  },
  'node-button-default': {
    type: {
      resolvedName: 'Button',
    },
    nodes: [],
    props: {
      id: '',
      href: '',
      size: 'lg',
      text: 'Adicionar bloco',
      label: 'Chamar para ação',
      width: '100%',
      border: {
        color: '#CBD5F5',
        style: 'solid',
        width: 20,
      },
      height: 'auto',
      margin: 0,
      shadow: 'soft',
      padding: 0,
      variant: 'solid',
      iconName: 'Airplay',
      showIcon: false,
      alignment: 'center',
      className: '',
      fullWidth: false,
      textColor: 'rgba(255, 255, 255, 1.00)',
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'rgba(0, 149, 255, 1.00)',
      showShadow: true,
      borderRadius: 120,
      openInNewTab: true,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Botão',
    linkedNodes: {},
  },
  'node-heading-default': {
    type: {
      resolvedName: 'Heading',
    },
    nodes: [],
    props: {
      id: '',
      seo: {
        text: 'Apresente o principal benefício com um título impactante.',
        level: 'h2',
      },
      text: 'Bem-vindo ao novo editor',
      align: 'center',
      color: '#1f1843',
      level: 'h2',
      width: '100%',
      border: {
        color: '#000000',
        style: 'dashed',
        width: 10,
      },
      height: 'auto',
      margin: 0,
      shadow: 'none',
      weight: 'bold',
      padding: 0,
      emphasis: false,
      maxWidth: '1200px',
      className: '',
      textAlign: 'center',
      uppercase: false,
      visibleOn: {
        mobile: true,
        tablet: true,
        desktop: true,
      },
      background: 'transparent',
      borderRadius: 0,
      spacingBelow: 16,
    },
    custom: {},
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Título',
    linkedNodes: {},
  },
};

export default nodes;
